zoning.exe:
	g++ -std=c++11 -I /usr/include/gdal -I ../../tilingtools/libtilingtools/ -L ../../tilingtools/libtilingtools/ classifier.cpp zoning.cpp -o zoning.exe -l gdal -l tilingtools -l sqlite3 -l gd -l pthread	
	
	
	
	